server:
  port: 8082

spring:
  application:
    name: config-server # 应用名称
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tomzhangv/config-repo #配置文件所在仓库地址
#          force-pull: true
#          uri: git@github.com:tomzhangv/config-repo #配置文件所在仓库地址
#          username: tom_zhangv@163.com
#          password: 310vv.VV
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

  security:
    user:
      name: user
      password: 123456

#指定当前eureka客户端的注册地址,
eureka:
  client:
    service-url:
      defaultZone: http://peer1:10081/eureka/,http://peer2:10082/eureka/

#度量指标监控与检查
management:
  endpoints:
    web:
      base-path: /actuator   #访问端点根路径，默认为 /actuator
      exposure:
        #        include: '*'         #需要开启的端点，这里主要是refresh这个端点
        include: bus-refresh         #需要开启的端点，这里主要是refresh这个端点
#        exclude:             #不需要开启的端点

#logging:
#  level:
#    com.netflix.discovery: 'OFF'
#    org.springframework.cloud: 'DEBUG'

