server:
  port: 8083
spring:
  application:
    name: config-server # 应用名称
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tomzhangv/config-repo #配置文件所在仓库地址
#          force-pull: true
#          uri: git@github.com:tomzhangv/config-repo #配置文件所在仓库地址
#          username: tom_zhangv@163.com
#          password: 310vv.VV
  security:
    user:
      name: user
      password: 123456
---
#spring:
#  profiles: configserver1
#server:
#  port: 10087
# 指定当前eureka客户端的注册地址,
#eureka:
#  client:
#    service-url:
#      defaultZone: http://peer1:10081/eureka/,http://peer2:10082/eureka/,http://peer3:10083/eureka
---
#spring:
#  profiles: configserver2
#server:
#  port: 10088
# 指定当前eureka客户端的注册地址,
#eureka:
#  client:
#    service-url:
#      defaultZone: http://peer1:10081/eureka/,http://peer2:10082/eureka/,http://peer3:10083/eureka
---

#logging:
#  level:
#    com.netflix.discovery: 'OFF'
#    org.springframework.cloud: 'DEBUG'

